package com.secondmonday.hodith.data.backup

import com.secondmonday.hodith.data.CaseEntity
import com.secondmonday.hodith.data.EventEntity
import com.secondmonday.hodith.data.EventTagCrossRef
import com.secondmonday.hodith.data.HunchEntity
import com.secondmonday.hodith.data.TagEntity
import com.secondmonday.hodith.data.TriggerEntity
import com.squareup.moshi.JsonClass

/** Bumped only if a future change makes an older export unreadable by [BackupSerializer]. */
const val BACKUP_SCHEMA_VERSION = 1

/**
 * Full-database export/import shape (spec §16): every entity table, as-is, with original
 * autogenerated ids intact. Import is a full restore (see [com.secondmonday.hodith.data.HodithRepository.importBackupData]),
 * not a merge, so ids never need remapping.
 */
@JsonClass(generateAdapter = true)
data class BackupData(
    val schemaVersion: Int = BACKUP_SCHEMA_VERSION,
    val cases: List<CaseEntity>,
    val tags: List<TagEntity>,
    val events: List<EventEntity>,
    val eventTags: List<EventTagCrossRef>,
    val hunches: List<HunchEntity>,
    val triggers: List<TriggerEntity>,
)
